language: python
os: linux
env:
  - CFLAGS="-shared -fPIC -std=c++0x"
before_install:
  - python --version
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest -v
after_success:
  - codecov
jobs:
  include:
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.7"
      python: 3.7
    - stage: format
      python: 3.7
      install: pip install autopep8
      before_script: " "
      script:
        - python setup.py check_format --directory docs --file-type python
        - python setup.py check_format --directory minkit --file-type python
        - python setup.py check_format --directory test --file-type python
