language: python
os: linux
env:
  - CFLAGS="-shared -fPIC -std=c++0x"
before_install:
  - python --version
  - sudo apt-get install libgsl-dev libxkbcommon-x11-0
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest -v
after_success:
  - codecov
jobs:
  include:
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.8"
      python: 3.8
    - stage: format
      python: 3.7
      before_script:
        - sudo apt-get install clang-format
        - pip install autopep8
        - pip install pyflakes
      script:
        - python setup.py check_copyright --regex "(minkit|test|docs|performance)$"
        - python setup.py check_format --regex "(minkit|test|docs|performance)$"
        - python setup.py check_pyflakes --regex "(minkit|test|docs|performance)$"
        - python setup.py check_documentation
      after_success: " "
    - stage: documentation
      python: 3.7
      install:
        - sudo apt-get install pandoc graphviz
        - pip install -r requirements.txt
        - pip install .
        - pip install -r docs/requirements.txt
      script:
        - mkdir html-docs
        - cd docs
        - BUILDDIR=../html-docs make html
      after_success: " "
